Added support to provide moesif-base-uri URI and bump up the version.
Moesif/moesifapi-csharp pull request #17
Opened 2022-08-25 21:27 UTC by praves77

2022-08-25 21:30 UTC, dgilling approved these changes

2022-08-26 22:50 UTC, keyur9 requested changes
We need to bump the version in nuspec

2022-08-26 23:14 UTC, praves77 commented
@keyur9 updated the version in nutspec.

2022-08-26 23:15 UTC, keyur9 approved these changes

2022-08-26 23:20 UTC, merged